# Generated by Django 3.2.7 on 2021-10-01 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('Bengal', 'Bengal'), ('California', 'California'), ('Texas', 'Texas')], max_length=150)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('doc_file', models.FileField(upload_to='extra_files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
