# Generated by Django 3.2.7 on 2021-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(choices=[('Bengal', 'Bengal'), ('California', 'California'), ('Texas', 'Texas'), ('state 4', 'state 4')], max_length=150),
        ),
    ]
